### PR TITLE
Update 404.html

### PR DESCRIPTION
**Pull request by ab-rahman92**
we have updated your code kindly accept our invitation

### CODE REVIEW

**Comment by samdutton** [comment]
I can't see any change — am I missing something?

**Comment by samdutton** [comment]
Marking as spam. Please let me know if this is somehow incorrect.

Was this done as part of Hacktoberfest?

**Comment by ab-rahman92** [comment]
Yeah, it's for hacktober fest.

**Comment by samdutton** [comment]
Is your PR meant to do anything?

**Comment by ab-rahman92** [comment]
Yeah, to contribute anything

**Pull request closed without merging**
