### PR TITLE
Create README pointing to the demo

### PR DESCRIPTION
**Pull request by dandv**
Would it help to have these READMEs in the root dir of each sample, pointing to the live demo?

The main use case is GitHub or web searches landing somewhere in the sample, and making it easy for the dev to go to the demo.

### CODE REVIEW

**Comment by samdutton** [comment]
I don't have time to write these right now, but I like the idea.

**Comment by dandv** [comment]
I volunteer to write READMEs like this one for the pages I land on.

**Comment by samdutton** [comment]
Thank you!

**Comment by dandv** [comment]
Any chance to pull this in?

**Comment by samdutton** [comment]
Oops — sorry! Merged.

**Comment by samdutton** [comment]
Huh — thought I'd merged this... Done now :).

**Pull request merged**
